# Generated by Django 5.1.5 on 2025-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('read_count', models.IntegerField(default=0)),
            ],
        ),
    ]
